services:
    LSB\ContractorBundle\Factory\ContractorFactory: ~
    lsb_contractor_factory_contractor:
        alias: 'LSB\ContractorBundle\Factory\ContractorFactory'
    LSB\ContractorBundle\Factory\ContractorFactoryInterface: '@LSB\ContractorBundle\Factory\ContractorFactory'



    LSB\ContractorBundle\Factory\GroupFactory: ~
    lsb_contractor_factory_group:
        alias: 'LSB\ContractorBundle\Factory\GroupFactory'
    LSB\ContractorBundle\Factory\GroupFactoryInterface: '@LSB\ContractorBundle\Factory\GroupFactory'



    LSB\ContractorBundle\Factory\ContractorGroupFactory: ~
    lsb_contractor_factory_contractor_group:
        alias: 'LSB\ContractorBundle\Factory\ContractorGroupFactory'
    LSB\ContractorBundle\Factory\ContractorGroupFactoryInterface: '@LSB\ContractorBundle\Factory\ContractorGroupFactory'



    LSB\ContractorBundle\Factory\ContactPersonFactory: ~
    lsb_contractor_factory_contact_person:
        alias: 'LSB\ContractorBundle\Factory\ContactPersonFactory'
    LSB\ContractorBundle\Factory\ContactPersonFactoryInterface: '@LSB\ContractorBundle\Factory\ContactPersonFactory'

