services:

    LSB\ContractorBundle\Repository\ContractorRepository:
        arguments:
            - '@doctrine'

    LSB\ContractorBundle\Repository\ContractorRepositoryInterface: '@LSB\ContractorBundle\Repository\ContractorRepository'


    LSB\ContractorBundle\Repository\ContractorGroupRepository:
        arguments:
            - '@doctrine'

    LSB\ContractorBundle\Repository\ContractorGroupRepositoryInterface: '@LSB\ContractorBundle\Repository\ContractorGroupRepository'


    LSB\ContractorBundle\Repository\ContractorGroupRelationRepository:
        arguments:
            - '@doctrine'

    LSB\ContractorBundle\Repository\ContractorGroupRelationRepositoryInterface: '@LSB\ContractorBundle\Repository\ContractorGroupRelationRepository'


    LSB\ContractorBundle\Repository\ContactPersonRepository:
        arguments:
            - '@doctrine'

    LSB\ContractorBundle\Repository\ContactPersonRepositoryInterface: '@LSB\ContractorBundle\Repository\ContactPersonRepository'


