services:

    LSB\ContractorBundle\Repository\ContractorRepository:
        arguments:
            - '@doctrine'

    LSB\ContractorBundle\Repository\ContractorRepositoryInterface: '@LSB\ContractorBundle\Repository\ContractorRepository'


    LSB\ContractorBundle\Repository\GroupRepository:
        arguments:
            - '@doctrine'

    LSB\ContractorBundle\Repository\GroupRepositoryInterface: '@LSB\ContractorBundle\Repository\GroupRepository'


    LSB\ContractorBundle\Repository\ContractorGroupRepository:
        arguments:
            - '@doctrine'

    LSB\ContractorBundle\Repository\ContractorGroupRepositoryInterface: '@LSB\ContractorBundle\Repository\ContractorGroupRepository'


    LSB\ContractorBundle\Repository\ContactPersonRepository:
        arguments:
            - '@doctrine'

    LSB\ContractorBundle\Repository\ContactPersonRepositoryInterface: '@LSB\ContractorBundle\Repository\ContactPersonRepository'


